### ISSUE TITLE
Reddit instructions not correct

### ISSUE THREAD

**Issue by artelse** [aimindseye/hisense-a9#1]
The reddit instructions failed for me because `./fastboot flash boot boot.img` is incorrect, it should be:
```
./fastboot flash boot_a boot.img
./fastboot flash boot_b boot.img
```
You might like to add this to the link.

**Comment by aimindseye** [comment]
Thanks, i'm just working on the draft still.

I have fixed root instructions to include both boot\_a and boot\_b flashing.
